#!/bin/bash

# Fetch data
USERNAME=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo "$NAME $VERSION")
UPTIME=$(uptime -p)
CPU_INFO=$(lshw -class processor | grep -m 1 "product" | awk -F ": " '{print $2}')
CPU_SPEED=$(lshw -class processor | grep -m 1 "capacity" | awk '{print $2}')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISK_INFO=$(lsblk -o NAME,MODEL,SIZE | grep -v "loop" | grep "disk")
VIDEO_CARD=$(lshw -class display | grep -m 1 "product" | awk -F ": " '{print $2}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(systemd-resolve --status | grep "DNS Servers" -A 1 | tail -n 1 | awk '{print $1}')
NETWORK_CARD=$(lshw -class network | grep -m 1 "product" | awk -F ": " '{print $2}')
NET_IP=$(ip -4 addr show | grep -m 1 "inet" | awk '{print $2}')

# System Status
LOGGED_USERS=$(who | awk '{print $1}' | paste -sd "," -)
DISK_SPACE=$(df -h --output=source,avail | grep "^/")
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVG=$(uptime | awk -F "load average: " '{print $2}')
MEMORY_ALLOC=$(free -h)
LISTENING_PORTS=$(ss -ltn | awk 'NR>1 {print $4}' | cut -d':' -f2 | paste -sd "," -)
UFW_RULES=$(sudo ufw status)

# Output
cat <<EOF

System Report generated by $USERNAME, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU_INFO
Speed: $CPU_SPEED
RAM: $RAM
Disk(s): 
$DISK_INFO
Video: $VIDEO_CARD

Network Information
--------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

InterfaceName: $NETWORK_CARD
IP Address: $NET_IP

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space: 
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Memory Allocation:
$MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules:
$UFW_RULES

EOF
